export const countriesList = [
  {
    name_en: 'Afghanistan',
    name_fa: 'افغانستان',
    dial_code: '+93',
    iso2: 'AF',
    flag_emoji: '🇦🇫',
    flag_svg: 'https://flagcdn.com/w40/af.png',
  },
  {
    name_en: 'Albania',
    name_fa: 'آلبانی',
    dial_code: '+355',
    iso2: 'AL',
    flag_emoji: '🇦🇱',
    flag_svg: 'https://flagcdn.com/w40/al.png',
  },
  {
    name_en: 'Algeria',
    name_fa: 'الجزایر',
    dial_code: '+213',
    iso2: 'DZ',
    flag_emoji: '🇩🇿',
    flag_svg: 'https://flagcdn.com/w40/dz.png',
  },
  {
    name_en: 'Argentina',
    name_fa: 'آرژانتین',
    dial_code: '+54',
    iso2: 'AR',
    flag_emoji: '🇦🇷',
    flag_svg: 'https://flagcdn.com/w40/ar.png',
  },
  {
    name_en: 'Australia',
    name_fa: 'استرالیا',
    dial_code: '+61',
    iso2: 'AU',
    flag_emoji: '🇦🇺',
    flag_svg: 'https://flagcdn.com/w40/au.png',
  },
  {
    name_en: 'Austria',
    name_fa: 'اتریش',
    dial_code: '+43',
    iso2: 'AT',
    flag_emoji: '🇦🇹',
    flag_svg: 'https://flagcdn.com/w40/at.png',
  },
  {
    name_en: 'Azerbaijan',
    name_fa: 'آذربایجان',
    dial_code: '+994',
    iso2: 'AZ',
    flag_emoji: '🇦🇿',
    flag_svg: 'https://flagcdn.com/w40/az.png',
  },
  {
    name_en: 'Bahrain',
    name_fa: 'بحرین',
    dial_code: '+973',
    iso2: 'BH',
    flag_emoji: '🇧🇭',
    flag_svg: 'https://flagcdn.com/w40/bh.png',
  },
  {
    name_en: 'Bangladesh',
    name_fa: 'بنگلادش',
    dial_code: '+880',
    iso2: 'BD',
    flag_emoji: '🇧🇩',
    flag_svg: 'https://flagcdn.com/w40/bd.png',
  },
  {
    name_en: 'Belgium',
    name_fa: 'بلژیک',
    dial_code: '+32',
    iso2: 'BE',
    flag_emoji: '🇧🇪',
    flag_svg: 'https://flagcdn.com/w40/be.png',
  },
  {
    name_en: 'Brazil',
    name_fa: 'برزیل',
    dial_code: '+55',
    iso2: 'BR',
    flag_emoji: '🇧🇷',
    flag_svg: 'https://flagcdn.com/w40/br.png',
  },
  {
    name_en: 'Canada',
    name_fa: 'کانادا',
    dial_code: '+1',
    iso2: 'CA',
    flag_emoji: '🇨🇦',
    flag_svg: 'https://flagcdn.com/w40/ca.png',
  },
  {
    name_en: 'China',
    name_fa: 'چین',
    dial_code: '+86',
    iso2: 'CN',
    flag_emoji: '🇨🇳',
    flag_svg: 'https://flagcdn.com/w40/cn.png',
  },
  {
    name_en: 'France',
    name_fa: 'فرانسه',
    dial_code: '+33',
    iso2: 'FR',
    flag_emoji: '🇫🇷',
    flag_svg: 'https://flagcdn.com/w40/fr.png',
  },
  {
    name_en: 'Germany',
    name_fa: 'آلمان',
    dial_code: '+49',
    iso2: 'DE',
    flag_emoji: '🇩🇪',
    flag_svg: 'https://flagcdn.com/w40/de.png',
  },
  {
    name_en: 'India',
    name_fa: 'هند',
    dial_code: '+91',
    iso2: 'IN',
    flag_emoji: '🇮🇳',
    flag_svg: 'https://flagcdn.com/w40/in.png',
  },
  {
    name_en: 'Iran',
    name_fa: 'ایران',
    dial_code: '+98',
    iso2: 'IR',
    flag_emoji: '🇮🇷',
    flag_svg: 'https://flagcdn.com/w40/ir.png',
  },
  {
    name_en: 'Iraq',
    name_fa: 'عراق',
    dial_code: '+964',
    iso2: 'IQ',
    flag_emoji: '🇮🇶',
    flag_svg: 'https://flagcdn.com/w40/iq.png',
  },
  {
    name_en: 'Italy',
    name_fa: 'ایتالیا',
    dial_code: '+39',
    iso2: 'IT',
    flag_emoji: '🇮🇹',
    flag_svg: 'https://flagcdn.com/w40/it.png',
  },
  {
    name_en: 'Japan',
    name_fa: 'ژاپن',
    dial_code: '+81',
    iso2: 'JP',
    flag_emoji: '🇯🇵',
    flag_svg: 'https://flagcdn.com/w40/jp.png',
  },
  {
    name_en: 'Pakistan',
    name_fa: 'پاکستان',
    dial_code: '+92',
    iso2: 'PK',
    flag_emoji: '🇵🇰',
    flag_svg: 'https://flagcdn.com/w40/pk.png',
  },
  {
    name_en: 'Russia',
    name_fa: 'روسیه',
    dial_code: '+7',
    iso2: 'RU',
    flag_emoji: '🇷🇺',
    flag_svg: 'https://flagcdn.com/w40/ru.png',
  },
  {
    name_en: 'Saudi Arabia',
    name_fa: 'عربستان',
    dial_code: '+966',
    iso2: 'SA',
    flag_emoji: '🇸🇦',
    flag_svg: 'https://flagcdn.com/w40/sa.png',
  },
  {
    name_en: 'Turkey',
    name_fa: 'ترکیه',
    dial_code: '+90',
    iso2: 'TR',
    flag_emoji: '🇹🇷',
    flag_svg: 'https://flagcdn.com/w40/tr.png',
  },
  {
    name_en: 'United Arab Emirates',
    name_fa: 'امارات',
    dial_code: '+971',
    iso2: 'AE',
    flag_emoji: '🇦🇪',
    flag_svg: 'https://flagcdn.com/w40/ae.png',
  },
  {
    name_en: 'United Kingdom',
    name_fa: 'انگلیس',
    dial_code: '+44',
    iso2: 'GB',
    flag_emoji: '🇬🇧',
    flag_svg: 'https://flagcdn.com/w40/gb.png',
  },
  {
    name_en: 'United States',
    name_fa: 'آمریکا',
    dial_code: '+1',
    iso2: 'US',
    flag_emoji: '🇺🇸',
    flag_svg: 'https://flagcdn.com/w40/us.png',
  },
];
