export const province = [
  { id: 1, name: 'آذربایجان شرقی', slug: 'East-Azerbaijan', code: 'EAZ', tel_prefix: '041' },
  { id: 2, name: 'آذربایجان غربی', slug: 'West-Azerbaijan', code: 'WAZ', tel_prefix: '044' },
  { id: 3, name: 'اردبیل', slug: 'Ardabil', code: 'ADL', tel_prefix: '045' },
  { id: 4, name: 'اصفهان', slug: 'Isfahan', code: 'ESF', tel_prefix: '031' },
  { id: 5, name: 'البرز', slug: 'Alborz', code: 'ABZ', tel_prefix: '026' },
  { id: 6, name: 'ایلام', slug: 'Ilam', code: 'ILM', tel_prefix: '084' },
  { id: 7, name: 'بوشهر', slug: 'Bushehr', code: 'BHR', tel_prefix: '077' },
  { id: 8, name: 'تهران', slug: 'Tehran', code: 'THR', tel_prefix: '021' },
  {
    id: 9,
    name: 'چهارمحال و بختیاری',
    slug: 'Chaharmahal-Bakhtiari',
    code: 'CHB',
    tel_prefix: '038',
  },
  { id: 10, name: 'خراسان جنوبی', slug: 'South-Khorasan', code: 'SKH', tel_prefix: '056' },
  { id: 11, name: 'خراسان رضوی', slug: 'Razavi-Khorasan', code: 'RKH', tel_prefix: '051' },
  { id: 12, name: 'خراسان شمالی', slug: 'North-Khorasan', code: 'NKH', tel_prefix: '058' },
  { id: 13, name: 'خوزستان', slug: 'Khuzestan', code: 'KHZ', tel_prefix: '061' },
  { id: 14, name: 'زنجان', slug: 'Zanjan', code: 'ZJN', tel_prefix: '024' },
  { id: 15, name: 'سمنان', slug: 'Semnan', code: 'SMN', tel_prefix: '023' },
  { id: 16, name: 'سیستان و بلوچستان', slug: 'Sistan-Baluchestan', code: 'SBN', tel_prefix: '054' },
  { id: 17, name: 'فارس', slug: 'Fars', code: 'FRS', tel_prefix: '071' },
  { id: 18, name: 'قزوین', slug: 'Qazvin', code: 'GZN', tel_prefix: '028' },
  { id: 19, name: 'قم', slug: 'Qom', code: 'QHM', tel_prefix: '025' },
  { id: 20, name: 'کردستان', slug: 'Kurdistan', code: 'KRD', tel_prefix: '087' },
  { id: 21, name: 'کرمان', slug: 'Kerman', code: 'KRN', tel_prefix: '034' },
  { id: 22, name: 'کرمانشاه', slug: 'Kermanshah', code: 'KRH', tel_prefix: '083' },
  {
    id: 23,
    name: 'کهگیلویه و بویراحمد',
    slug: 'Kohgiluyeh-Boyer-Ahmad',
    code: 'KBD',
    tel_prefix: '074',
  },
  { id: 24, name: 'گلستان', slug: 'Golestan', code: 'GLS', tel_prefix: '017' },
  { id: 25, name: 'لرستان', slug: 'Lorestan', code: 'LRS', tel_prefix: '066' },
  { id: 26, name: 'گیلان', slug: 'Gilan', code: 'GIL', tel_prefix: '013' },
  { id: 27, name: 'مازندران', slug: 'Mazandaran', code: 'MZN', tel_prefix: '011' },
  { id: 28, name: 'مرکزی', slug: 'Markazi', code: 'MKZ', tel_prefix: '086' },
  { id: 29, name: 'هرمزگان', slug: 'Hormozgan', code: 'HRZ', tel_prefix: '076' },
  { id: 30, name: 'همدان', slug: 'Hamedan', code: 'HDN', tel_prefix: '081' },
  { id: 31, name: 'یزد', slug: 'Yazd', code: 'YZD', tel_prefix: '035' },
];
