export const pages = [
  '/',
  '/product',
  '/product-category',
  '/mag',
  '/about-us',
  '/brands',
  '/common-questions',
  '/contact-us',
  '/guide',
  '/product_brand',
  '/product-tag',
  '/result',
  '/mag/sitemap',
  '/shop',
  '/site-error-report',
  '/profile',
  '/cart',
  '/address',
  '/checkout',
  '/home',
  '/license',
  '/auth',
  '/verify',
  '/admin',
  '/festival',
  '/buy-now-pay-later',
  '/rosetime',
  '/nowruz-white-rose',
  '/yalda-festival',
  '/buy-one-get-two',
  '/search-and-win-a-prize',
  '/love-day',
  '/mother-day',
  '/fortune-wheel',
  '/career-opportunities',
  '/low-price-products',
  '/spring-and-summer-products',
  '/fathers-day',
  '/summer-off',
  '/magazine',
  '/pages',
  '/too-many-request',
  '/products',
  '/print',
  '/dev',
];

export const noIndexPaths = ['/admin', '/auth', '/search', '/shop', '*/page/*'];

export const gonePaths = [
  '/product-tag/',
  '/shop/',
  '/benchmark/',
  '/brands/',
  '/برند/',
  '/%D8%A8%D8%B1%D9%86%D8%AF/',
] as string[];

export const protectedRoute = ['/checkout', '/address', '/admin', '/profile'];
